"use strict";

export const research =  {
  //tier 0
  nodes:{
    manaStorage: {
      id: "manaStorage",
      name: "Mana Storage",
      desc: "",
      x: -1000,
      y: -600,
      resources: [],
      parents: [],
    },
    stoneMining: {
      id: "stoneMining",
      name: "Stone Mining",
      desc: "",
      x: -1000,
      y: -200,
      resources: [],
      parents: [],
    },
    woodGolems: {
      id: "woodGolems",
      name: "Wood Golems",
      desc: "",
      x: -1000,
      y: 200,
      resources: [],
      parents: [],
    },
    extraStorage: {
      id: "extraStorage",
      name: "Extra Storage",
      desc: "",
      x: -1000,
      y: 600,
      resources: [],
      parents: [],
    },
  // tier1: {
    manaProduction: {
      id: "manaProduction",
      name: "Mana Production",
      desc: "",
      x: -500,
      y: -600,
      resources: [],
      parents: [],
    },
    coalMining: {
      id: "coalMining",
      name: "Coal Mining",
      desc: "",
      x: -500,
      y: -200,
      resources: [],
      parents: [],
    },
    stoneGolems: {
      id: "stoneGolems",
      name: "Stone Golems",
      desc: "",
      x: -500,
      y: 200,
      resources: [],
      parents: [],
    },
    logistics1: {
      id: "logistics1",
      name: "Logistics I",
      desc: "",
      x: -500,
      y: 600,
      resources: [],
      parents: [],
    },
    clayProf: {
      id: "clayProf",
      name: "Clay Golems - Proficiency",
      desc: "",
      x: -666,
      y: 1000,
      resources: [],
      parents: [],
    },
    woodProf: {
      id: "woodProf",
      name: "Wood Golems - Proficiency",
      desc: "",
      x: -333,
      y: 1000,
      resources: [],
      parents: [],
    },
  // tier2: 
    manaGenerator: {
      id: "manaGenerator",
      name: "Mana Generator",
      desc: "",
      x: 0,
      y: -800,
      resources: [],
      parents: [],
    },
    forge: {
      id: "forge",
      name: "Forge",
      desc: "",
      x: 0,
      y: -400,
      resources: [],
      parents: [],
    },
    copperMining: {
      id: "copperMining",
      name: "Copper Mining",
      desc: "",
      x: 0,
      y: 0,
      resources: [],
      parents: [],
    },
    expeditions: {
      id: "expeditions",
      name: "Expeditions",
      desc: "",
      x: 0,
      y: 400,
      resources: [],
      parents: [],
    },
    stoneProf: {
      id: "stoneProf",
      name: "Stone Golems - Proficiency",
      desc: "",
      x: 0,
      y: 1000,
      resources: [],
      parents: [],
    },
  // tier3: {
    spellcasting: {
      id: "spellcasting",
      name: "Spellcasting",
      desc: "",
      x: 500,
      y: -800,
      resources: [],
      parents: [],
    },
    oreProcessing: {
      id: "oreProcessing",
      name: "Ore Processing",
      desc: "",
      x: 500,
      y: -400,
      resources: [],
      parents: [],
    },
    ironMining: {
      id: "ironMining",
      name: "Iron Mining",
      desc: "",
      x: 500,
      y: 0,
      resources: [],
      parents: [],
    },
    logistics2: {
      id: "logistics2",
      name: "Logistics II",
      desc: "",
      x: 500,
      y: 600,
      resources: [],
      parents: [],
    },
    copperGolems: {
      id: "copperGolems",
      name: "Copper Golems",
      desc: "",
      x: 500,
      y: 1000,
      resources: [],
      parents: [],
    },
  // tier4: 
    alchemicalCentrifuge: {
      id: "alchemicalCentrifuge",
      name: "Alchemical Centrifuge",
      desc: "",
      x: 1000,
      y: -1000,
      resources: [],
      parents: [],
    },
    alchemicalRefining: {
      id: "alchemicalRefining",
      name: "Alchemical Refining",
      desc: "",
      x: 1000,
      y: -600,
      resources: [],
      parents: [],
    },
    steel: {
      id: "steel",
      name: "Steel",
      desc: "",
      x: 1000,
      y: -200,
      resources: [],
      parents: [],
    },
    galenaMining: {
      id: "galenaMining",
      name: "Galena Mining",
      desc: "",
      x: 1000,
      y: 200,
      resources: [],
      parents: [],
    },
    copperProf: {
      id: "copperProf",
      name: "Copper Golems - Proficiency",
      desc: "",
      x: 1000,
      y: 1000,
      resources: [],
      parents: [],
    },
  // },
  // tier5: {
  //   crystalMining: {
  //     id: "crystalMining",
  //     name: "Crystal Mining",
  //     desc: "",
  //     y: 21.42,
  //     resources: [],
  //   },
  //   molybdochalkos: {
  //     id: "molybdochalkos",
  //     name: "Molybdochalkos",
  //     desc: "",
  //     y: 35.7,
  //     resources: [],
  //   },
  //   goldMining: {
  //     id: "goldMining",
  //     name: "Gold Mining",
  //     desc: "",
  //     y: 49.98,
  //     resources: [],
  //   },
  //   meteoriteMining: {
  //     id: "meteoriteMining",
  //     name: "Meteorite Mining",
  //     desc: "",
  //     y: 64.26,
  //     resources: [],
  //   },
  // }
  // ironGolems: {
  //   id: "ironGolems",
  //   name: "Iron Golems",
  //   desc: "",
  //   y: 92.82,
  //   resources: [],
  // },
  }
}