"use strict";

export const research =  {
  tier0: {
      manaStorage: {
        id: "manaStorage",
        name: "Mana Storage",
        desc: "",
        y: 14.28,
        resources: [],
      },
      stoneMining: {
        id: "stoneMining",
        name: "Stone Mining",
        desc: "",
        y: 42.84,
        resources: [],
      },
      woodGolems: {
        id: "woodGolems",
        name: "Wood Golems",
        desc: "",
        y: 64.26,
        resources: [],
      },
      extraStorage: {
        id: "extraStorage",
        name: "Extra Storage",
        desc: "",
        y: 85.68,
        resources: [],
      },
  },
  tier1: {
      clayProf: {
        id: "clayProf",
        name: "Clay Golems - Proficiency",
        desc: "",
        y: 92.82,
        resources: [],
      },
      manaProduction: {
        id: "manaProduction",
        name: "Mana Production",
        desc: "",
        y: 14.28,
        resources: [],
      },
      coalMining: {
        id: "coalMining",
        name: "Coal Mining",
        desc: "",
        y: 42.84,
        resources: [],
      },
  },
  tier2: {
      spellcasting: {
        id: "spellcasting",
        name: "Spellcasting",
        desc: "",
        y: 7.14,
        resources: [],
      },
      manaGenerator: {
        id: "manaGenerator",
        name: "Mana Generator",
        desc: "",
        y: 21.42,
        resources: [],
      },
      forge: {
        id: "forge",
        name: "Forge",
        desc: "",
        y: 35.7,
        resources: [],
      },
      copperMining: {
        id: "copperMining",
        name: "Copper Mining",
        desc: "",
        y: 49.98,
        resources: [],
      },
      logistics1: {
        id: "logistics1",
        name: "Logistics I",
        desc: "",
        y: 78.54,
        resources: [],
      },
      woodProf: {
        id: "woodProf",
        name: "Wood Golems - Proficiency",
        desc: "",
        y: 92.82,
        resources: [],
      },
      stoneGolems: {
        id: "stoneGolems",
        name: "Stone Golems",
        desc: "",
        y: 64.26,
        resources: [],
      },
  },
  tier3: {
      alchemicalCentrifuge: {
        id: "alchemicalCentrifuge",
        name: "Alchemical Centrifuge",
        desc: "",
        y: 14.28,
        resources: [],
      },
      oreProcessing: {
        id: "oreProcessing",
        name: "Ore Processing",
        desc: "",
        y: 35.7,
        resources: [],
      },
      ironMining: {
        id: "ironMining",
        name: "Iron Mining",
        desc: "",
        y: 49.98,
        resources: [],
      },
      expeditions: {
        id: "expeditions",
        name: "Expeditions",
        desc: "",
        y: 64.26,
        resources: [],
      },
      stoneProf: {
        id: "stoneProf",
        name: "Stone Golems - Proficiency",
        desc: "",
        y: 92.82,
        resources: [],
      },
  },
  tier4: {
    alchemicalRefining: {
      id: "alchemicalRefining",
      name: "Alchemical Refining",
      desc: "",
      y: 14.28,
      resources: [],
    },
    steel: {
      id: "steel",
      name: "Steel",
      desc: "",
      y: 35.7,
      resources: [],
    },
    galenaMining: {
      id: "galenaMining",
      name: "Galena Mining",
      desc: "",
      y: 49.98,
      resources: [],
    },
    logistics2: {
      id: "logistics2",
      name: "Logistics II",
      desc: "",
      y: 78.54,
      resources: [],
    },
    ironGolems: {
      id: "ironGolems",
      name: "Iron Golems",
      desc: "",
      y: 92.82,
      resources: [],
    },
  },
  tier5: {
    crystalMining: {
      id: "crystalMining",
      name: "Crystal Mining",
      desc: "",
      y: 21.42,
      resources: [],
    },
    molybdochalkos: {
      id: "molybdochalkos",
      name: "Molybdochalkos",
      desc: "",
      y: 35.7,
      resources: [],
    },
    goldMining: {
      id: "goldMining",
      name: "Gold Mining",
      desc: "",
      y: 49.98,
      resources: [],
    },
    meteoriteMining: {
      id: "meteoriteMining",
      name: "Meteorite Mining",
      desc: "",
      y: 64.26,
      resources: [],
    },
    ironProf: {
      id: "copperProf",
      name: "Iron Golems - Proficiency",
      desc: "",
      y: 92.82,
      resources: [],
    },
  }
}
